# Generated by Django 4.1.7 on 2023-03-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="facility_parent_id",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Идентификатор родительского объекта",
            ),
        ),
        migrations.AlterField(
            model_name="facilitytype",
            name="node_type_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Идентификатор типа узла"
            ),
        ),
    ]
