# Generated by Django 4.1.7 on 2023-03-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0002_alter_facility_facility_parent_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="cluster_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Идентификатор куста"
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="dept_id",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Привязка к подразделению (месторождению)",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="facility_actual",
            field=models.BooleanField(
                blank=True, default=1, null=True, verbose_name="Актуальность объекта"
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="facility_coord_lng",
            field=models.FloatField(blank=True, null=True, verbose_name="Долгота"),
        ),
        migrations.AlterField(
            model_name="facility",
            name="facility_coord_ltd",
            field=models.FloatField(blank=True, null=True, verbose_name="Широта"),
        ),
        migrations.AlterField(
            model_name="facility",
            name="facility_mode_id",
            field=models.IntegerField(
                blank=True,
                default="1",
                help_text="1 - Актуальный, 2 - Тест, 3 - Не актуальный",
                null=True,
                verbose_name="Режим объекта",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="facility_name",
            field=models.CharField(
                blank=True,
                max_length=40,
                null=True,
                unique=True,
                verbose_name="Название объекта",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="facility_position",
            field=models.IntegerField(
                blank=True, null=True, unique=True, verbose_name="Позиция"
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="facility_process_rate",
            field=models.SmallIntegerField(
                blank=True, default="30", null=True, verbose_name="Период обновления"
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="facility_type_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Идентификатор типа объекта"
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="field_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Идентификатор месторождения"
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="script_id",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Идентификатор на вид обработки в интерфейсе",
            ),
        ),
    ]
