# Generated by Django 4.1.7 on 2023-03-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0004_alter_facility_facility_create_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="facility_name",
            field=models.CharField(
                default=1, max_length=40, verbose_name="Название объекта"
            ),
            preserve_default=False,
        ),
    ]
