# Generated by Django 4.1.7 on 2023-03-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0005_alter_facility_facility_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="property_expression",
            field=models.CharField(
                blank=True,
                max_length=1000,
                null=True,
                verbose_name="Выражение свойства",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_is_not_calc_rate",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Свойство не рассчитано"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_is_use_active_facility_flange",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Свойство использует активный фланец объекта",
            ),
        ),
    ]
