# Generated by Django 4.1.7 on 2023-03-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0006_alter_property_property_expression_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="property_formula",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="Формула свойства"
            ),
        ),
    ]
