# Generated by Django 4.1.7 on 2023-03-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0008_alter_property_property_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facilitytype",
            name="event_category_mast",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Битовая маска"
            ),
        ),
        migrations.AlterField(
            model_name="facilitytype",
            name="node_type_id",
            field=models.IntegerField(
                default=1, verbose_name="Идентификатор типа узла"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="form",
            name="form_desc",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Описание формы"
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="form_settings",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="Настройки формы"
            ),
        ),
    ]
