# Generated by Django 4.1.7 on 2023-03-12 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0009_alter_facilitytype_event_category_mast_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_date_confirm",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата подтверждения события"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type_base_id",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Идентификатор базового типа события",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="property_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="server.property",
                verbose_name="Идентификатор свойства",
            ),
        ),
    ]
